Add support for class changing items
jjppof/goldensun_html5 pull request #184
Opened 2021-01-01 12:20 UTC by immortaleeb

This adds support for class changing items.

As an example, I implemented the _Mysterious Card_ item which gives characters the class _Pierrot_ along with all of its abilities.

<img width="533" alt="mysterious_card" src="https://user-images.githubusercontent.com/1183783/103438510-f016c800-4c33-11eb-9387-791d61cc65ca.png">

<img width="521" alt="pierrot_psynergies" src="https://user-images.githubusercontent.com/1183783/103438518-fb69f380-4c33-11eb-9772-50228de542ea.png">

2021-01-03 17:11 UTC, jjppof commented on assets/dbs/abilities_db.json
> +        "effects": [
We need the 0.2 chance here.
![image](https://user-images.githubusercontent.com/7890647/103484429-92b67e80-4dcd-11eb-802b-c79b3f307625.png)

2021-01-03 17:19 UTC, jjppof commented on base/MainChar.ts
> +        const equiped_class_changer = "equip_slots" in this && this.equip_slots[equip_slots.CLASS_CHANGER];
no need to check `"equip_slots" in this`

2021-01-03 17:26 UTC, jjppof commented on base/MainChar.ts
> +        if (item.type === item_types.CLASS_CHANGER) {
please use `else if`, so we don't need to check the `item.type` again. Also, after updating the class, we need to update the attributes, so I suggest moving `this.update_attributes();` from line 303 to just after these if elses checks.

2021-01-03 17:27 UTC, jjppof commented on base/MainChar.ts
> +        if (item.type === item_types.CLASS_CHANGER) {
Same logic from the last comment in `equip_item` function.

2021-01-03 17:32 UTC, jjppof commented on base/Classes.ts
> +import {Item} from "./Item";
Please remove this unnecessary import.

2021-01-03 17:37 UTC, jjppof requested changes
Excellent work! Thanks a lot! Just change those small issues and we are ready to go.

2021-01-03 17:55 UTC, bfcferreira commented on base/windows/item/ClassChangeWithItemWindow.ts
> +        this.class_name_arrow_blink_timer.start();
Why do Start/Stop here and Resume down below when you can just start the timer in the "open" function?

2021-01-03 17:55 UTC, bfcferreira commented on base/windows/item/ItemOptionsWindow.ts
> +        console.log(text);
Console logs should never be in final commits

2021-01-13 18:44 UTC, jjppof approved these changes

2021-01-13 18:44 UTC, merged