Replaces Webpack with Esbuild for faster bundling
jjppof/goldensun_html5 pull request #306
Opened 2021-06-27 16:16 UTC by heyjordn

Hi, great work on making this, however when I try to bundle the project, the build times are so long, I switched out Webpack with [Esbuild](https://esbuild.github.io/) and the build times are down to seconds now. 

Could you review and let me know if this could work?

2021-06-28 01:26 UTC, jjppof commented
Hi! Thanks for the PR!
It seems that esbuild is really faster, but we need to have the same dev environment as webpack in order to start using it. For instance, in the way you set `npm start`, the application is just watching the changes, but not serving the application. Please check [webpack.config.js](https://github.com/jjppof/goldensun_html5/blob/master/webpack.config.js) and set esbuild to have the same behavior as webpack.
Also, don't forget to add esbuild to dev dependencies in package.json and remove webpack.

2021-06-29 01:48 UTC, heyjordn commented
Hey @jjppof I've added in `esbuild-serve` for serving the assets along with a quick build time, testing on my end and it seems to be working

2021-06-29 21:00 UTC, jjppof commented on package.json
> +    "_postinstall": "husky install",
why the underscore before `postinstall`?

2021-06-29 21:00 UTC, jjppof commented on package.json
> +    "phaser-ce": "^2.18.0",
Please remove this, gshtml5 uses a custom Phaser.

2021-06-29 21:01 UTC, jjppof commented on esbuild.config.js
> +    target: ["es2019", "chrome58", "firefox57"],
I don't think we need `chrome58` and `firefox57` targets. Is there a reason for them?

2021-06-29 21:03 UTC, jjppof commented on webpack.config.js
> -      ignored: [
We also need this ignore list on `esbuild-serve`.

2021-06-30 13:53 UTC, jjppof requested changes
Please set to `es2017` and add an ignore list in the watcher.

2021-07-01 02:04 UTC, jjppof commented on tsconfig.json
>          "./static/*.js",
Need to add esbuild.config.js to this list.

2021-07-01 02:10 UTC, jjppof commented on package.json
> +    "esbuild-serve": "^1.0.1",
I was checking this package and it has only 13 stars on Github, I usually avoid packages with little engagement like this one. But it seems that esbuild already has an internal functionality to serve applications, [see](https://esbuild.github.io/api/#serve). If it fits for our case, using only esbuild is preferable.

2021-07-01 02:12 UTC, jjppof requested changes
Changes in /assets folder are not causing the browser to reload. Also, would be nice if on `npm start` the browser open just like we had with webpack.

2021-07-04 16:55 UTC, heyjordn commented
Hey @jjppof I had to switch to [estrella](https://github.com/rsms/estrella), another esbuild build too to rebuild when `assets` changed, looking into the open broswer feature,

2021-07-05 02:30 UTC, jjppof commented on package.json
> +    "typescript": "^4.3.4"
Please downgrade typescript version to 4.2.X in order to have compatibility with typedocs.

2021-07-05 02:42 UTC, jjppof commented on scripts/build.js
> +scandir(dir, filter, { recursive: true }).then((files) => {
`files` is not being used here.

2021-07-05 02:42 UTC, jjppof commented on scripts/build.js
> +      changes.map((c) => console.log(`Reloading ${file} -> ${file}`));
`c` is not being used here.

2021-07-05 02:58 UTC, jjppof requested changes
I got this error when changing something inside assets folder (assets\filters\reveal.js specifically):

> Unhandled exception: ReferenceError: file is not defined

Also, please change `serve-http`  (which is 24 stars only) to [`http-server`](https://github.com/http-party/http-server). Use the `-o` and `-c-1` (very important) options.

Since you are using a third-party package to serve, why not using raw `esbuild`? It also has [watch callback](https://esbuild.github.io/api/#watch).

2022-04-13 04:42 UTC, MilesBHuff commented
@heyjordn This PR needs to merge the latest changes from `master` -- the configs are rather different now.

2022-04-13 13:52 UTC, jjppof commented
I think we can close this one for now. We can think of a faster bundler for a next release.

2022-04-13 13:52 UTC, closed without merging