add Djinn Set Status Event
jjppof/goldensun_html5 pull request #361
Opened 2022-01-23 21:17 UTC by bearda59

Fairly simple event designed to solve https://github.com/jjppof/goldensun_html5/issues/333

I tried to follow the emoticon event as a guide

2022-01-24 02:51 UTC, jjppof requested changes
Many thanks for considering helping us! Just do those small changes I said in the other comment and we are fine to merge.
Thanks!

2022-01-24 23:05 UTC, bearda59 commented on base/game_events/DjinnSetStatusEvent.ts
> +            this.djinn.set_status(this.status, this.character);
should be fixed in the most recent commit.

2022-01-25 02:59 UTC, jjppof commented
Please run `npm run format` and do a last commit. The entire code looks fine, just need this formatting so github can accept the merge. I could have done it for you, but I don't have permission to push into your master. Many thanks!

2022-01-25 02:59 UTC, jjppof approved these changes

2022-01-25 13:57 UTC, jjppof approved these changes

2022-01-25 13:57 UTC, merged