Add sfx djinn set/unset, and djinn trade/give, asset for level up sfx
jjppof/goldensun_html5 pull request #465
Opened 2023-01-04 02:58 UTC by SamuelPhang

Working towards issue: https://github.com/users/jjppof/projects/1/views/1

2023-01-04 13:04 UTC, jjppof commented on base/windows/djinn/DjinnListWindow.ts
> +    public djinn_chosen: boolean;
Let's see whether those `this.grant_full_user_control()` calls are necessary. Then we can decide whether this variable is truly necessary.

2023-01-04 13:06 UTC, jjppof requested changes
Many thanks for the help!
Let's confirm the necessity of `this.grant_full_user_control()` calls. Please see the comments.
The sfx conditions when setting the controls are fine.

2023-01-04 17:30 UTC, SamuelPhang commented on base/windows/djinn/DjinnListWindow.ts
> +                if (!this.setting_djinn_status) this.grant_full_user_control();
Every time the cursor is moved we need to update the sfx connected to the R button to make sure it plays the correct sound when setting/unsetting a djinn. So I added this call to each function that is bound to a direction pad button press. Let me know if there's a better way

2023-01-04 18:53 UTC, jjppof commented on base/windows/djinn/DjinnListWindow.ts
> +                if (!this.setting_djinn_status) this.grant_full_user_control();
Got it. And yeah, there's no better way, but I'll do some changes in ControlManager to support this. I'll let you know. Thanks!

2023-01-08 02:52 UTC, jjppof approved these changes

2023-01-08 02:52 UTC, merged